export const MENUITEMS = [
  {
    menutitle: "MAIN",
    Items: [
      {
        path: `${process.env.PUBLIC_URL}/dashboard`,
        icon: "fe fe-home",
        type: "link",
        active: false,
        selected: false,
        title: "Dashboard",
      },
    ],
  },
  {
    menutitle: "UI KIT",

    Items: [
      {
        title: "Apps",
        icon: "fe fe-slack",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${process.env.PUBLIC_URL}/apps/carddesigns`,
            type: "link",
            active: false,
            selected: false,
            title: "Cards-design",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/chat`,
            type: "link",
            active: false,
            selected: false,
            title: "Chat",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/charts`,
            type: "link",
            active: false,
            selected: false,
            title: "Charts",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/scrollbar`,
            type: "link",
            active: false,
            selected: false,
            title: "Content-Scrollbar",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/counter`,
            type: "link",
            active: false,
            selected: false,
            title: "Counters",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/cryptocurrencies`,
            type: "link",
            active: false,
            selected: false,
            title: "Crypto-Currencies",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/defaultcalender`,
            type: "link",
            active: false,
            selected: false,
            title: "Default-Calender",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/footer`,
            type: "link",
            active: false,
            selected: false,
            title: "Footers",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/fullcalender`,
            type: "link",
            active: false,
            selected: false,
            title: "Full-Calender",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/loader`,
            type: "link",
            active: false,
            selected: false,
            title: "Loaders",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/notification`,
            type: "link",
            active: false,
            selected: false,
            title: "Notifications",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/rangeslider`,
            type: "link",
            active: false,
            selected: false,
            title: "Range-slider",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/rating`,
            type: "link",
            active: false,
            selected: false,
            title: "Rating",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/search`,
            type: "link",
            active: false,
            selected: false,
            title: "Search",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/sweet`,
            type: "link",
            active: false,
            selected: false,
            title: "Sweet-alerts",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/timeline`,
            type: "link",
            active: false,
            selected: false,
            title: "Timeline",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/treeview`,
            type: "link",
            active: false,
            selected: false,
            title: "TreeView",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/userlist`,
            type: "link",
            active: false,
            selected: false,
            title: "User-list",
          },
          {
            path: `${process.env.PUBLIC_URL}/apps/widgets`,
            type: "link",
            active: false,
            selected: false,
            title: "Widgets",
          },
        ],
      },
      {
        title: "Bootstrap",
        icon: "fe fe-package",
        type: "sub",
        active: false,
        selected: false,
        Names: "mega-slide-menu",
        Name: "mega-menu",
        children: [
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/accordian`,
            type: "link",
            active: false,
            selected: false,
            title: "Accordians",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/bootstrapalerts`,
            type: "link",
            active: false,
            selected: false,
            title: "Alerts",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/avatarradius`,
            type: "link",
            active: false,
            selected: false,
            title: "Avatar-Radius",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/avatarsquare`,
            type: "link",
            active: false,
            selected: false,
            title: "Avatar-Square",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/avatarrounded`,
            type: "link",
            active: false,
            selected: false,
            title: "Avatar-Rounded",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/badgespills`,
            type: "link",
            active: false,
            selected: false,
            title: "BadgesPills",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/breadcrumbs`,
            type: "link",
            active: false,
            selected: false,
            title: "Breadcrumbs",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/buttons`,
            type: "link",
            active: false,
            selected: false,
            title: "Buttons",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/carousels`,
            type: "link",
            active: false,
            selected: false,
            title: "Carousels",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/colors`,
            type: "link",
            active: false,
            selected: false,
            title: "Colors",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/dropdowns`,
            type: "link",
            active: false,
            selected: false,
            title: "DropDowns",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/listgroups`,
            type: "link",
            active: false,
            selected: false,
            title: "List-Groups",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/mediaobject`,
            type: "link",
            active: false,
            selected: false,
            title: "Media-Object",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/modal`,
            type: "link",
            active: false,
            selected: false,
            title: "Modal",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/navigation`,
            type: "link",
            active: false,
            selected: false,
            title: "Navigation",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/offcanvas`,
            type: "link",
            active: false,
            selected: false,
            title: "OffCanvas",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/pagination`,
            type: "link",
            active: false,
            selected: false,
            title: "Pagination",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/panels`,
            type: "link",
            active: false,
            selected: false,
            title: "Panels",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/progress`,
            type: "link",
            active: false,
            selected: false,
            title: "Progress",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/tabs`,
            type: "link",
            active: false,
            selected: false,
            title: "Tabs",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/tags`,
            type: "link",
            title: "Tags",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/thumbnails`,
            type: "link",
            title: "Thumbnails",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/toast`,
            type: "link",
            title: "Toast",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/tooltippopover`,
            type: "link",
            title: "Tooltip Popover",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/typography`,
            type: "link",
            title: "Typography",
          },
          {
            path: `${process.env.PUBLIC_URL}/bootstrap/ribbons`,
            type: "link",
            title: "Ribbons",
          },
        ],
      },

      {
        path: `${process.env.PUBLIC_URL}/landingPage/landingPage`,
        badge: "badge bg-green br-5 side-badge blink-text pb-1",
        badgetxt: "New",
        icon: "fe fe-zap",
        type: "link",
        active: true,
        selected: false,
        title: "Landing Page",
      },
    ],
  },
  {
    menutitle: "PRE-BUILD-PAGES",
    Items: [
      {
        title: "Pages",
        icon: "fe fe-layers",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${process.env.PUBLIC_URL}/pages/editprofile`,
            type: "link",
            active: false,
            selected: false,
            title: "Edit-profile",
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/gallery`,
            type: "link",
            active: false,
            selected: false,
            title: "Gallery",
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/mailcompose`,
            type: "link",
            active: false,
            selected: false,
            title: "Mail-compose",
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/mailinbox`,
            type: "link",
            active: false,
            selected: false,
            title: "Mail-inbox",
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/mailread`,
            type: "link",
            active: false,
            selected: false,
            title: "Mail-read",
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/notificationlist`,
            type: "link",
            active: false,
            selected: false,
            title: "Notification-list",
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/profile`,
            type: "link",
            active: false,
            selected: false,
            title: "Profile",
          },

          {
            title: "Forms",
            icon: "ti-face-smile",
            type: "sub",
            Name: "",
            Names: "",
            active: false,
            selected: false,
            children: [
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/formadvanced`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-advanced",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/formeditor`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-editor",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/formelements`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-elements",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/formlayouts`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-layouts",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/formvalidation`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-validation",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/formwizard`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-wizard",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/forms/forminputspinner`,
                type: "link",
                active: false,
                selected: false,
                title: "Form-input-spinner",
              },
            ],
          },
          {
            title: "Table",
            icon: "ti-face-smile",
            type: "sub",
            Name: "",
            Names: "",
            active: false,
            selected: false,
            children: [
              {
                path: `${process.env.PUBLIC_URL}/pages/tables/datatables`,
                type: "link",
                active: false,
                selected: false,
                title: "Data-Table",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/tables/defaulttables`,
                type: "link",
                active: false,
                selected: false,
                title: "Default-Table",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/tables/edittables`,
                type: "link",
                active: false,
                selected: false,
                title: "Edit-Table",
              },
            ],
          },
          {
            title: "Extension",
            icon: "ti-face-smile",
            type: "sub",
            Name: "",
            Names: "",
            active: false,
            selected: false,
            children: [
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/aboutcompany`,
                type: "link",
                active: false,
                selected: false,
                title: "About Company",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/blogdetails`,
                type: "link",
                active: false,
                selected: false,
                title: "Blog Details",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/blogpost`,
                type: "link",
                active: false,
                selected: false,
                title: "Blog Post",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/blogs`,
                type: "link",
                active: false,
                selected: false,
                title: "Blogs",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/emptypage`,
                type: "link",
                active: false,
                selected: false,
                title: "EmptyPage",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/faqs`,
                type: "link",
                active: false,
                selected: false,
                title: "FAQS",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/invoice`,
                type: "link",
                active: false,
                selected: false,
                title: "Invoice",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/pricing`,
                type: "link",
                active: false,
                selected: false,
                title: "Pricing Table",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/services`,
                type: "link",
                active: false,
                selected: false,
                title: "Services",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/setting`,
                type: "link",
                active: false,
                selected: false,
                title: "Settings",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/term`,
                type: "link",
                active: false,
                selected: false,
                title: "Terms",
              },
              {
                path: `${process.env.PUBLIC_URL}/pages/extension/underconstruction`,
                type: "link",
                active: false,
                selected: false,
                title: "UnderConstruction",
              },
            ],
          },
          {
            path: `${process.env.PUBLIC_URL}/pages/switcher/switcherstyle1`,
            type: "link",
            active: false,
            selected: false,
            title: "Switcher",
          },
        ],
      },
      {
        title: "E-commerce",
        icon: "fe fe-shopping-bag",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${process.env.PUBLIC_URL}/ecommerce/addproduct`,
            type: "link",
            active: false,
            selected: false,
            title: "Add Product",
          },
          {
            path: `${process.env.PUBLIC_URL}/ecommerce/checkout`,
            type: "link",
            active: false,
            selected: false,
            title: "Checkout",
          },
          {
            path: `${process.env.PUBLIC_URL}/ecommerce/productdetails`,
            type: "link",
            active: false,
            selected: false,
            title: "Product Details",
          },
          {
            path: `${process.env.PUBLIC_URL}/ecommerce/shop`,
            type: "link",
            active: false,
            selected: false,
            title: "Shop",
          },
          {
            path: `${process.env.PUBLIC_URL}/ecommerce/shoppingcart`,
            type: "link",
            active: false,
            selected: false,
            title: "ShoppingCart",
          },
          {
            path: `${process.env.PUBLIC_URL}/ecommerce/wishlist`,
            type: "link",
            active: false,
            selected: false,
            title: "Wishlist",
          },
        ],
      },
      {
        title: "File-Manager",
        icon: "fe fe-folder",
        badge: "badge bg-pink side-badge",
        badgetxt: "4",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${process.env.PUBLIC_URL}/filemanager/fileattachments`,
            type: "link",
            active: false,
            selected: false,
            title: "File-Attachments",
          },
          {
            path: `${process.env.PUBLIC_URL}/filemanager/filedetails`,
            type: "link",
            active: false,
            selected: false,
            title: "File Details",
          },
          {
            path: `${process.env.PUBLIC_URL}/filemanager/filemanager`,
            type: "link",
            active: false,
            selected: false,
            title: "File Manager",
          },
          {
            path: `${process.env.PUBLIC_URL}/filemanager/filemanagerlist`,
            type: "link",
            active: false,
            selected: false,
            title: "File-ManagerList",
          },
        ],
      },
    ],
  },

  {
    menutitle: "MISC PAGES",
    Items: [
      {
        title: "Authentication",
        icon: "fe fe-users",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${process.env.PUBLIC_URL}/authentication/login`,
            type: "link",
            active: false,
            selected: false,
            title: "Login",
          },
          {
            path: `${process.env.PUBLIC_URL}/authentication/register`,
            type: "link",
            active: false,
            selected: false,
            title: "Register",
          },
          {
            path: `${process.env.PUBLIC_URL}/authentication/forgotpassword`,
            type: "link",
            active: false,
            selected: false,
            title: "Forgot Password",
          },
          {
            path: `${process.env.PUBLIC_URL}/authentication/lockscreen`,
            type: "link",
            active: false,
            selected: false,
            title: "LockScreen",
          },
          {
            title: "ErrorPage",
            icon: "ti-face-smile",
            type: "sub",
            Name: "",
            Names: "",
            active: false,
            selected: false,
            children: [
              {
                path: `${process.env.PUBLIC_URL}/authentication/errorpage/error400`,
                type: "link",
                active: false,
                selected: false,
                title: "Error400",
              },
              {
                path: `${process.env.PUBLIC_URL}/authentication/errorpage/error401`,
                type: "link",
                active: false,
                selected: false,
                title: "Error401",
              },
              {
                path: `${process.env.PUBLIC_URL}/authentication/errorpage/error403`,
                type: "link",
                active: false,
                selected: false,
                title: "Error403",
              },
              {
                path: `${process.env.PUBLIC_URL}/authentication/errorpage/error404`,
                type: "link",
                active: false,
                selected: false,
                title: "Error404",
              },
              {
                path: `${process.env.PUBLIC_URL}/authentication/errorpage/error500`,
                type: "link",
                active: false,
                selected: false,
                title: "Error500",
              },
              {
                path: `${process.env.PUBLIC_URL}/authentication/errorpage/error503`,
                type: "link",
                active: false,
                selected: false,
                title: "Error503",
              },
            ],
          },
        ],
      },
    ],
  },

  {
    menutitle: "GENERAL",
    Items: [
      {
        title: "Maps",
        icon: "fe fe-map-pin",
        type: "sub",
        Name: "",
        Names: "",
        children: [
          {
            path: `${process.env.PUBLIC_URL}/maps/leafletmaps`,
            type: "link",
            active: false,
            selected: false,
            title: "Leaflet-Maps",
          },
          {
            path: `${process.env.PUBLIC_URL}/maps/simplemaps`,
            type: "link",
            active: false,
            selected: false,
            title: "Simple-Maps",
          },
        ],
      },
      {
        title: "Charts",
        icon: "fe fe-bar-chart-2",
        type: "sub",
        Name: "",
        Names: "",
        badge: "badge bg-secondary side-badge",
        badgetxt: "6",
        children: [
          {
            path: `${process.env.PUBLIC_URL}/charts/chartjs`,
            type: "link",
            active: false,
            selected: false,
            title: " Chartjs",
          },
          {
            path: `${process.env.PUBLIC_URL}/charts/echart`,
            type: "sub",
            Name: "",
            Names: "",
            title: " Echart",
            children: [
              {
                path: `${process.env.PUBLIC_URL}/charts/echart/lines`,
                type: "link",
                active: false,
                selected: false,
                title: " Line Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/echart/bar`,
                type: "link",
                active: false,
                selected: false,
                title: " Bar Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/echart/candlestick`,
                type: "link",
                active: false,
                selected: false,
                title: " Candle Stick Chart",
              },

              {
                path: `${process.env.PUBLIC_URL}/charts/echart/scatter`,
                type: "link",
                active: false,
                selected: false,
                title: " Scatter Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/echart/tree`,
                type: "link",
                active: false,
                selected: false,
                title: " Tree Chart",
              },
            ],
          },

          {
            path: `${process.env.PUBLIC_URL}/charts/apexchart`,
            type: "sub",
            Name: "",
            Names: "",
            title: " ApexChart",
            children: [
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/line`,
                type: "link",
                active: false,
                selected: false,
                title: " Line Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/area`,
                type: "link",
                active: false,
                selected: false,
                title: " Area Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/column`,
                type: "link",
                active: false,
                selected: false,
                title: " Column Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/bar`,
                type: "link",
                active: false,
                selected: false,
                title: " Bar Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/mixed`,
                type: "link",
                active: false,
                selected: false,
                title: " Mixed Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/timeline`,
                type: "link",
                active: false,
                selected: false,
                title: " Timeline Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/candlestick`,
                type: "link",
                active: false,
                selected: false,
                title: " CandleStick Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/boxplot`,
                type: "link",
                active: false,
                selected: false,
                title: " Boxplot Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/treemap`,
                type: "link",
                active: false,
                selected: false,
                title: " Treemap Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/pie`,
                type: "link",
                active: false,
                selected: false,
                title: " Pie Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/radialbar`,
                type: "link",
                active: false,
                selected: false,
                title: " Radialbar Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/radar`,
                type: "link",
                active: false,
                selected: false,
                title: " Radar Chart",
              },
              {
                path: `${process.env.PUBLIC_URL}/charts/apexchart/polararea`,
                type: "link",
                active: false,
                selected: false,
                title: " PolarArea Chart",
              },
            ],
          },
        ],
      },
      {
        title: "Icons",
        icon: "fe fe-wind",
        type: "sub",
        Name: "",
        Names: "",
        children: [
          {
            path: `${process.env.PUBLIC_URL}/icons/bootstrapicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Bootstrap Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/feathericons`,
            type: "link",
            active: false,
            selected: false,
            title: " Feather Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/flagicons`,
            type: "link",
            active: false,
            selected: false,
            title: " Flag Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/fontawesome`,
            type: "link",
            active: false,
            selected: false,
            title: "Font-Awesome Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/ionicicons`,
            type: "link",
            active: false,
            selected: false,
            title: " Ionic Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/materialdesignicons`,
            type: "link",
            active: false,
            selected: false,
            title: " MaterialDesign Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/pe7icons`,
            type: "link",
            active: false,
            selected: false,
            title: " Pe7 Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/simplelineicons`,
            type: "link",
            active: false,
            selected: false,
            title: "Simpleline Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/themifyicons`,
            type: "link",
            active: false,
            selected: false,
            title: " Themify Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/typiconsicons`,
            type: "link",
            active: false,
            selected: false,
            title: " Typicons Icons",
          },
          {
            path: `${process.env.PUBLIC_URL}/icons/weathericons`,
            type: "link",
            active: false,
            selected: false,
            title: " Weather Icons",
          },
        ],
      },
    ],
  },
];
export const EXECUTIVEMENUITEMS = [
  {
    menutitle: "Dashboard",
    Items: [
      {
        path: `${process.env.PUBLIC_URL}/dashboard`,
        icon: "fe fe-home",
        type: "link",
        active: true,
        selected: false,
        title: "Dashboard",
      },
    ],
  },
   // {
      //     title: 'Projects', icon: "fe fe-folder", type: 'sub', path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/project/ACG`, type: 'link', active: false, selected: false, title: 'ACG' },
      //         { path: `${process.env.PUBLIC_URL}/project/FAP`, type: 'link', active: false, selected: false, title: 'FAP' },
      //         { path: `${process.env.PUBLIC_URL}/project/CF`, type: 'link', active: false, selected: false, title: 'CF' },
      //         { path: `${process.env.PUBLIC_URL}/project/Westhaven, Waterloo`, type: 'link', active: false, selected: false, title: 'Westhaven, Waterloo' },

      //     ]
      // },
  {
    menutitle: "Masters",

    Items: [
      {
        path: `${process.env.PUBLIC_URL}/admin/users`,
        icon: "fe fe-user-plus",
        type: "link",
        active: false,
        selected: false,
        title: "Users",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Contacts`,
        icon: "fe fe-user",
        type: "link",
        active: false,
        selected: false,
        title: "Contacts",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Task`,
        icon: "fe fe-user",
        type: "link",
        active: false,
        selected: false,
        title: "Task Master",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Registered_customers`,
        icon: "fe fe-user",
        type: "link",
        active: false,
        selected: false,
        title: "Accounts",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Templates`,
        icon: "fe fe-shopping-bag",
        type: "link",
        active: false,
        selected: false,
        title: "Templates",
      },

      {
        path: `${process.env.PUBLIC_URL}/admin/projectsData`,
        icon: "fe fe-briefcase",
        type: "link",
        active: false,
        selected: false,
        title: "Projects Master",
      },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/ProjectFinancial`,
      //   icon: "fe fe-briefcase",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Projects Financial",
      // },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/Quote`,
      //   icon: "fe fe-dollar-sign",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Quotes / Estimate",
      // },
      {
        path: `${process.env.PUBLIC_URL}/admin/tax`,
        icon: "fe fe-dollar-sign",
        type: "link",
        active: false,
        selected: false,
        title: "Tax Master",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/products`,
        icon: "fe fe-shopping-cart",
        type: "link",
        active: false,
        selected: false,
        title: "Product Master",
      },

      {
        path: `${process.env.PUBLIC_URL}/admin/Invoices`,
        icon: "fe fe-dollar-sign",
        type: "link",
        active: false,
        selected: false,
        title: "Invoices",
      },

      {
        path: `${process.env.PUBLIC_URL}/admin/leaveManagement`,
        icon: "fe fe-plus-square",
        type: "link",
        active: false,
        selected: false,
        title: "Leave Management",
      },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/pendingLeave`,
      //   icon: "fe fe-check-square",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Pending Leave",
      // },

      // { path: `${process.env.PUBLIC_URL}/admin/categories`, icon: 'fe fe-pocket', type: 'link', active: false, selected: false, title: 'Categories' },
      // { path: `${process.env.PUBLIC_URL}/admin/cities`, icon: 'fe fe-map', type: 'link', active: false, selected: false, title: 'Cities' },
      // { path: `${process.env.PUBLIC_URL}/admin/trips`, icon: 'fe fe-sunrise', type: 'link', active: false, selected: false, title: 'Trips' },
      // { path: `${process.env.PUBLIC_URL}/admin/slider_images`, icon: 'fe fe-image', type: 'link', active: false, selected: false, title: 'Slider Images' },
      // { path: `${process.env.PUBLIC_URL}/admin/sections`, icon: 'fe fe-crop', type: 'link', active: false, selected: false, title: 'Sections' },
      // { path: `${process.env.PUBLIC_URL}/admin/testimonials`, icon: 'fe fe-link', type: 'link', active: false, selected: false, title: 'Testimonials' },
      // { path: `${process.env.PUBLIC_URL}/admin/videos`, icon: 'fe fe-video', type: 'link', active: false, selected: false, title: 'Videos' },
      // { path: `${process.env.PUBLIC_URL}/admin/Registered_customers`, icon: 'fe fe-user', type: 'link', active: false, selected: false, title: 'Customers' },
      // { path: `${process.env.PUBLIC_URL}/admin/Bookings`, icon: 'fe fe-shopping-bag', type: 'link', active: false, selected: false, title: 'Bookings' },
      // { path: `${process.env.PUBLIC_URL}/admin/Coupons`, icon: 'fe fe-percent', type: 'link', active: false, selected: false, title: 'Coupons' },
      // { path: `${process.env.PUBLIC_URL}/admin/trips/archive`, icon: 'fe fe-sun', type: 'link', active: false, selected: false, title: 'Archive Trips' },
      // { path: `${process.env.PUBLIC_URL}/my_admin_enquires`, icon: 'fe fe-edit', type: 'link', active: false, selected: false, title: 'My Enquires' },
      // { path: `${process.env.PUBLIC_URL}/admin_enquires`, icon: 'fe fe-edit', type: 'link', active: false, selected: false, title: 'All Enquires' },
      // { path: `${process.env.PUBLIC_URL}/admin/Blogs`, icon: 'fe fe-type', type: 'link', active: false, selected: false, title: 'Blogs' },
      // { path: `${process.env.PUBLIC_URL}/admin/Jobs`, icon: 'fe fe-briefcase', type: 'link', active: false, selected: false, title: 'Carrers' },

      // { path: `${process.env.PUBLIC_URL}/dashboard`, icon: 'fe fe-home', type: 'link', active: true, selected: false, title: 'Dashboard' },

      // {
      //     title: 'Projects', icon: "fe fe-folder", type: 'sub', path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/project/ACG`, type: 'link', active: false, selected: false, title: 'ACG' },
      //         { path: `${process.env.PUBLIC_URL}/project/FAP`, type: 'link', active: false, selected: false, title: 'FAP' },
      //         { path: `${process.env.PUBLIC_URL}/project/CF`, type: 'link', active: false, selected: false, title: 'CF' },
      //         { path: `${process.env.PUBLIC_URL}/project/Westhaven, Waterloo`, type: 'link', active: false, selected: false, title: 'Westhaven, Waterloo' },

      //     ]
      // },
      {
        path: `${process.env.PUBLIC_URL}/admin/TimeSheet`,
        icon: "fe fe-clock",
        type: "link",
        active: false,
        selected: false,
        title: "Timesheet",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/ReportsTimeSheet`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "ReportsTimeSheet",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/ReportsTimeSheetProjectWise`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "Project TimeSheet",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/MultiProjectReport`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "Multiple Project TimeSheet",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/DateRangeReport`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "Date Range Project TimeSheet",
      },

      // // { path: `${process.env.PUBLIC_URL}/admin_purchases`, icon: 'fe fe-slack', type: 'link', active: false, selected: false, title: 'All Purchases' },
      // {
      //     title: 'Purchases', icon: "fe fe-shopping-cart", type: 'sub',Name:"",Names:"",
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_inprogress`, type: 'link', active: false, selected: false, title: 'In progress' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_reupload`, type: 'link', active: false, selected: false, title: ' Re-Upload' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_updated`, type: 'link', active: false, selected: false, title: 'Updated' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_rejected`, type: 'link', active: false, selected: false, title: 'Rejected' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_verified`, type: 'link', active: false, selected: false, title: 'Verified' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_all`, type: 'link', active: false, selected: false, title: 'All' },

      //         // { path: `${process.env.PUBLIC_URL}/icons/materialdesignicons`, type: 'link', active: false, selected: false, title: ' MaterialDesign Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/pe7icons`, type: 'link', active: false, selected: false, title: ' Pe7 Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/simplelineicons`, type: 'link', active: false, selected: false, title: 'Simpleline Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/themifyicons`, type: 'link', active: false, selected: false, title: ' Themify Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/typiconsicons`, type: 'link', active: false, selected: false, title: ' Typicons Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/weathericons`, type: 'link', active: false, selected: false, title: ' Weather Icons' },
      //     ]
      // },
      // // { path: `${process.env.PUBLIC_URL}/admin_customers`, icon: 'fe fe-gift', type: 'link', active: false, selected: false, title: 'Leader Boards' },
      // // { path: `${process.env.PUBLIC_URL}/admin_purchases`, icon: 'fe fe-slack', type: 'link', active: false, selected: false, title: 'All Purchases' },
      // {
      //     title: 'Leader Boards', icon: "fe fe-shopping-bag", type: 'sub',Name:"",Names:"",
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/LeaderBoardCustomer`, type: 'link', active: false, selected: false, title: 'Customers' },
      //         { path: `${process.env.PUBLIC_URL}/LeaderBoardDealer`, type: 'link', active: false, selected: false, title: 'Retailers' },

      //     ]
      // },
      // { path: `${process.env.PUBLIC_URL}/logout`, icon: 'fe fe-log-out', type: 'link', active: false, selected: false, title: 'Log Out' },
    ],
  },
];
export const ADMINMENUITEMS = [
  {
    menutitle: "Dashboard",
    Items: [
      {
        path: `${process.env.PUBLIC_URL}/dashboard`,
        icon: "fe fe-home",
        type: "link",
        active: true,
        selected: false,
        title: "Dashboard",
      },
    ],
  },
   // {
      //     title: 'Projects', icon: "fe fe-folder", type: 'sub', path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/project/ACG`, type: 'link', active: false, selected: false, title: 'ACG' },
      //         { path: `${process.env.PUBLIC_URL}/project/FAP`, type: 'link', active: false, selected: false, title: 'FAP' },
      //         { path: `${process.env.PUBLIC_URL}/project/CF`, type: 'link', active: false, selected: false, title: 'CF' },
      //         { path: `${process.env.PUBLIC_URL}/project/Westhaven, Waterloo`, type: 'link', active: false, selected: false, title: 'Westhaven, Waterloo' },

      //     ]
      // },
  {
    menutitle: "Masters",

    Items: [
      {
        path: `${process.env.PUBLIC_URL}/admin/users`,
        icon: "fe fe-user-plus",
        type: "link",
        active: false,
        selected: false,
        title: "Users",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Task`,
        icon: "fe fe-user-plus",
        type: "link",
        active: false,
        selected: false,
        title: "Users",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Contacts`,
        icon: "fe fe-user",
        type: "link",
        active: false,
        selected: false,
        title: "Contacts",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Registered_customers`,
        icon: "fe fe-user",
        type: "link",
        active: false,
        selected: false,
        title: "Accounts",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/Templates`,
        icon: "fe fe-shopping-bag",
        type: "link",
        active: false,
        selected: false,
        title: "Templates",
      },

      {
        path: `${process.env.PUBLIC_URL}/admin/projectsData`,
        icon: "fe fe-briefcase",
        type: "link",
        active: false,
        selected: false,
        title: "Projects Master",
      },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/ProjectFinancial`,
      //   icon: "fe fe-briefcase",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Projects Financial",
      // },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/Quote`,
      //   icon: "fe fe-dollar-sign",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Quotes / Estimate",
      // },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/tax`,
      //   icon: "fe fe-dollar-sign",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Tax Master",
      // },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/products`,
      //   icon: "fe fe-shopping-cart",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Product Master",
      // },

      // {
      //   path: `${process.env.PUBLIC_URL}/admin/Invoices`,
      //   icon: "fe fe-dollar-sign",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Invoices",
      // },

      {
        path: `${process.env.PUBLIC_URL}/admin/leaveManagement`,
        icon: "fe fe-plus-square",
        type: "link",
        active: false,
        selected: false,
        title: "Leave Management",
      },
      // {
      //   path: `${process.env.PUBLIC_URL}/admin/pendingLeave`,
      //   icon: "fe fe-check-square",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Pending Leave",
      // },

      // { path: `${process.env.PUBLIC_URL}/admin/categories`, icon: 'fe fe-pocket', type: 'link', active: false, selected: false, title: 'Categories' },
      // { path: `${process.env.PUBLIC_URL}/admin/cities`, icon: 'fe fe-map', type: 'link', active: false, selected: false, title: 'Cities' },
      // { path: `${process.env.PUBLIC_URL}/admin/trips`, icon: 'fe fe-sunrise', type: 'link', active: false, selected: false, title: 'Trips' },
      // { path: `${process.env.PUBLIC_URL}/admin/slider_images`, icon: 'fe fe-image', type: 'link', active: false, selected: false, title: 'Slider Images' },
      // { path: `${process.env.PUBLIC_URL}/admin/sections`, icon: 'fe fe-crop', type: 'link', active: false, selected: false, title: 'Sections' },
      // { path: `${process.env.PUBLIC_URL}/admin/testimonials`, icon: 'fe fe-link', type: 'link', active: false, selected: false, title: 'Testimonials' },
      // { path: `${process.env.PUBLIC_URL}/admin/videos`, icon: 'fe fe-video', type: 'link', active: false, selected: false, title: 'Videos' },
      // { path: `${process.env.PUBLIC_URL}/admin/Registered_customers`, icon: 'fe fe-user', type: 'link', active: false, selected: false, title: 'Customers' },
      // { path: `${process.env.PUBLIC_URL}/admin/Bookings`, icon: 'fe fe-shopping-bag', type: 'link', active: false, selected: false, title: 'Bookings' },
      // { path: `${process.env.PUBLIC_URL}/admin/Coupons`, icon: 'fe fe-percent', type: 'link', active: false, selected: false, title: 'Coupons' },
      // { path: `${process.env.PUBLIC_URL}/admin/trips/archive`, icon: 'fe fe-sun', type: 'link', active: false, selected: false, title: 'Archive Trips' },
      // { path: `${process.env.PUBLIC_URL}/my_admin_enquires`, icon: 'fe fe-edit', type: 'link', active: false, selected: false, title: 'My Enquires' },
      // { path: `${process.env.PUBLIC_URL}/admin_enquires`, icon: 'fe fe-edit', type: 'link', active: false, selected: false, title: 'All Enquires' },
      // { path: `${process.env.PUBLIC_URL}/admin/Blogs`, icon: 'fe fe-type', type: 'link', active: false, selected: false, title: 'Blogs' },
      // { path: `${process.env.PUBLIC_URL}/admin/Jobs`, icon: 'fe fe-briefcase', type: 'link', active: false, selected: false, title: 'Carrers' },

      // { path: `${process.env.PUBLIC_URL}/dashboard`, icon: 'fe fe-home', type: 'link', active: true, selected: false, title: 'Dashboard' },

      // {
      //     title: 'Projects', icon: "fe fe-folder", type: 'sub', path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/project/ACG`, type: 'link', active: false, selected: false, title: 'ACG' },
      //         { path: `${process.env.PUBLIC_URL}/project/FAP`, type: 'link', active: false, selected: false, title: 'FAP' },
      //         { path: `${process.env.PUBLIC_URL}/project/CF`, type: 'link', active: false, selected: false, title: 'CF' },
      //         { path: `${process.env.PUBLIC_URL}/project/Westhaven, Waterloo`, type: 'link', active: false, selected: false, title: 'Westhaven, Waterloo' },

      //     ]
      // },
      {
        path: `${process.env.PUBLIC_URL}/admin/TimeSheet`,
        icon: "fe fe-clock",
        type: "link",
        active: false,
        selected: false,
        title: "Timesheet",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/ReportsTimeSheetProjectWise`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "Project TimeSheet",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/ReportsTimeSheet`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "ReportsTimeSheet",
      },

      // // { path: `${process.env.PUBLIC_URL}/admin_purchases`, icon: 'fe fe-slack', type: 'link', active: false, selected: false, title: 'All Purchases' },
      // {
      //     title: 'Purchases', icon: "fe fe-shopping-cart", type: 'sub',Name:"",Names:"",
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_inprogress`, type: 'link', active: false, selected: false, title: 'In progress' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_reupload`, type: 'link', active: false, selected: false, title: ' Re-Upload' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_updated`, type: 'link', active: false, selected: false, title: 'Updated' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_rejected`, type: 'link', active: false, selected: false, title: 'Rejected' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_verified`, type: 'link', active: false, selected: false, title: 'Verified' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_all`, type: 'link', active: false, selected: false, title: 'All' },

      //         // { path: `${process.env.PUBLIC_URL}/icons/materialdesignicons`, type: 'link', active: false, selected: false, title: ' MaterialDesign Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/pe7icons`, type: 'link', active: false, selected: false, title: ' Pe7 Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/simplelineicons`, type: 'link', active: false, selected: false, title: 'Simpleline Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/themifyicons`, type: 'link', active: false, selected: false, title: ' Themify Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/typiconsicons`, type: 'link', active: false, selected: false, title: ' Typicons Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/weathericons`, type: 'link', active: false, selected: false, title: ' Weather Icons' },
      //     ]
      // },
      // // { path: `${process.env.PUBLIC_URL}/admin_customers`, icon: 'fe fe-gift', type: 'link', active: false, selected: false, title: 'Leader Boards' },
      // // { path: `${process.env.PUBLIC_URL}/admin_purchases`, icon: 'fe fe-slack', type: 'link', active: false, selected: false, title: 'All Purchases' },
      // {
      //     title: 'Leader Boards', icon: "fe fe-shopping-bag", type: 'sub',Name:"",Names:"",
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/LeaderBoardCustomer`, type: 'link', active: false, selected: false, title: 'Customers' },
      //         { path: `${process.env.PUBLIC_URL}/LeaderBoardDealer`, type: 'link', active: false, selected: false, title: 'Retailers' },

      //     ]
      // },
      // { path: `${process.env.PUBLIC_URL}/logout`, icon: 'fe fe-log-out', type: 'link', active: false, selected: false, title: 'Log Out' },
    ],
  },
];
export const EMPLOYEETEMS = [
  {
    menutitle: "Dashboard",
    Items: [
      {
        path: `${process.env.PUBLIC_URL}/dashboard`,
        icon: "fe fe-home",
        type: "link",
        active: true,
        selected: false,
        title: "Dashboard",
      },
    ],
  },
  {
    menutitle: "Masters",

    Items: [
      {
        path: `${process.env.PUBLIC_URL}/admin/profile`,
        icon: "fe fe-user-plus",
        type: "link",
        active: false,
        selected: false,
        title: "Profile",
      },
      {
        path: `${process.env.PUBLIC_URL}/admin/leaveManagement`,
        icon: "fe fe-plus-square",
        type: "link",
        active: false,
        selected: false,
        title: "Leave Management",
      },

      // {
      //   path: `${process.env.PUBLIC_URL}/admin/pendingLeave`,
      //   icon: "fe fe-check-square",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Pending Leave",
      // },

      // { path: `${process.env.PUBLIC_URL}/admin/categories`, icon: 'fe fe-pocket', type: 'link', active: false, selected: false, title: 'Categories' },
      // { path: `${process.env.PUBLIC_URL}/admin/cities`, icon: 'fe fe-map', type: 'link', active: false, selected: false, title: 'Cities' },
      // { path: `${process.env.PUBLIC_URL}/admin/trips`, icon: 'fe fe-sunrise', type: 'link', active: false, selected: false, title: 'Trips' },
      // { path: `${process.env.PUBLIC_URL}/admin/slider_images`, icon: 'fe fe-image', type: 'link', active: false, selected: false, title: 'Slider Images' },
      // { path: `${process.env.PUBLIC_URL}/admin/sections`, icon: 'fe fe-crop', type: 'link', active: false, selected: false, title: 'Sections' },
      // { path: `${process.env.PUBLIC_URL}/admin/testimonials`, icon: 'fe fe-link', type: 'link', active: false, selected: false, title: 'Testimonials' },
      // { path: `${process.env.PUBLIC_URL}/admin/videos`, icon: 'fe fe-video', type: 'link', active: false, selected: false, title: 'Videos' },
      // { path: `${process.env.PUBLIC_URL}/admin/Registered_customers`, icon: 'fe fe-user', type: 'link', active: false, selected: false, title: 'Customers' },
      // { path: `${process.env.PUBLIC_URL}/admin/Bookings`, icon: 'fe fe-shopping-bag', type: 'link', active: false, selected: false, title: 'Bookings' },
      // { path: `${process.env.PUBLIC_URL}/admin/Coupons`, icon: 'fe fe-percent', type: 'link', active: false, selected: false, title: 'Coupons' },
      // { path: `${process.env.PUBLIC_URL}/admin/trips/archive`, icon: 'fe fe-sun', type: 'link', active: false, selected: false, title: 'Archive Trips' },
      // { path: `${process.env.PUBLIC_URL}/my_admin_enquires`, icon: 'fe fe-edit', type: 'link', active: false, selected: false, title: 'My Enquires' },
      // { path: `${process.env.PUBLIC_URL}/admin_enquires`, icon: 'fe fe-edit', type: 'link', active: false, selected: false, title: 'All Enquires' },
      // { path: `${process.env.PUBLIC_URL}/admin/Blogs`, icon: 'fe fe-type', type: 'link', active: false, selected: false, title: 'Blogs' },
      // { path: `${process.env.PUBLIC_URL}/admin/Jobs`, icon: 'fe fe-briefcase', type: 'link', active: false, selected: false, title: 'Carrers' },

      // { path: `${process.env.PUBLIC_URL}/dashboard`, icon: 'fe fe-home', type: 'link', active: true, selected: false, title: 'Dashboard' },

      // {
      //     title: 'Projects', icon: "fe fe-folder", type: 'sub', path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/project/ACG`, type: 'link', active: false, selected: false, title: 'ACG' },
      //         { path: `${process.env.PUBLIC_URL}/project/FAP`, type: 'link', active: false, selected: false, title: 'FAP' },
      //         { path: `${process.env.PUBLIC_URL}/project/CF`, type: 'link', active: false, selected: false, title: 'CF' },
      //         { path: `${process.env.PUBLIC_URL}/project/Westhaven, Waterloo`, type: 'link', active: false, selected: false, title: 'Westhaven, Waterloo' },

      //     ]
      // },
      {
        path: `${process.env.PUBLIC_URL}/admin/TimeSheet`,
        icon: "fe fe-clock",
        type: "link",
        active: false,
        selected: false,
        title: "Timesheet",
      },

      // // { path: `${process.env.PUBLIC_URL}/admin_purchases`, icon: 'fe fe-slack', type: 'link', active: false, selected: false, title: 'All Purchases' },
      // {
      //     title: 'Purchases', icon: "fe fe-shopping-cart", type: 'sub',Name:"",Names:"",
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_inprogress`, type: 'link', active: false, selected: false, title: 'In progress' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_reupload`, type: 'link', active: false, selected: false, title: ' Re-Upload' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_updated`, type: 'link', active: false, selected: false, title: 'Updated' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_rejected`, type: 'link', active: false, selected: false, title: 'Rejected' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_verified`, type: 'link', active: false, selected: false, title: 'Verified' },
      //         { path: `${process.env.PUBLIC_URL}/admin_purchases_all`, type: 'link', active: false, selected: false, title: 'All' },

      //         // { path: `${process.env.PUBLIC_URL}/icons/materialdesignicons`, type: 'link', active: false, selected: false, title: ' MaterialDesign Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/pe7icons`, type: 'link', active: false, selected: false, title: ' Pe7 Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/simplelineicons`, type: 'link', active: false, selected: false, title: 'Simpleline Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/themifyicons`, type: 'link', active: false, selected: false, title: ' Themify Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/typiconsicons`, type: 'link', active: false, selected: false, title: ' Typicons Icons' },
      //         // { path: `${process.env.PUBLIC_URL}/icons/weathericons`, type: 'link', active: false, selected: false, title: ' Weather Icons' },
      //     ]
      // },
      // // { path: `${process.env.PUBLIC_URL}/admin_customers`, icon: 'fe fe-gift', type: 'link', active: false, selected: false, title: 'Leader Boards' },
      // // { path: `${process.env.PUBLIC_URL}/admin_purchases`, icon: 'fe fe-slack', type: 'link', active: false, selected: false, title: 'All Purchases' },
      // {
      //     title: 'Leader Boards', icon: "fe fe-shopping-bag", type: 'sub',Name:"",Names:"",
      //     children: [
      //         { path: `${process.env.PUBLIC_URL}/LeaderBoardCustomer`, type: 'link', active: false, selected: false, title: 'Customers' },
      //         { path: `${process.env.PUBLIC_URL}/LeaderBoardDealer`, type: 'link', active: false, selected: false, title: 'Retailers' },

      //     ]
      // },
      // { path: `${process.env.PUBLIC_URL}/logout`, icon: 'fe fe-log-out', type: 'link', active: false, selected: false, title: 'Log Out' },
    ],
  },
];
export const DEALERMENUITEMS = [
  {
    menutitle: "Dashboard",
    Items: [
      {
        path: `${process.env.PUBLIC_URL}/DealerDashboard`,
        icon: "fe fe-home",
        type: "link",
        active: true,
        selected: false,
        title: "Dashboard",
      },
      // { path: `${process.env.PUBLIC_URL}/dealer_customers`, icon: 'fe fe-users', type: 'link', active: true, selected: false, title: 'My Customers' },
      // { path: `${process.env.PUBLIC_URL}/dealer_purchases`, icon: 'fe fe-shopping-cart', type: 'link', active: true, selected: false, title: 'My Sales' },
    ],
  },
  // {
  //     menutitle: "Masters",

  //     Items: [
  //         {
  //             title: 'Dealers', icon: "fe fe-user-check", type: 'link',path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
  //         },
  //         { path: `${process.env.PUBLIC_URL}/admin_customers`, icon: 'fe fe-users', type: 'link', active: false, selected: false, title: 'Customers' },
  //         // { path: `${process.env.PUBLIC_URL}/logout`, icon: 'fe fe-log-out', type: 'link', active: false, selected: false, title: 'Log Out' },

  //     ]
  // },
];
export const CUSTOMERMENUITEMS = [
  {
    menutitle: "Dashboard",
    Items: [
      {
        path: `${process.env.PUBLIC_URL}/CustomerDashboard`,
        icon: "fe fe-home",
        type: "link",
        active: true,
        selected: false,
        title: "Dashboard",
      },
    ],
  },
  // {
  //     menutitle: "Masters",

  //     Items: [
  //         {
  //             title: 'Dealers', icon: "fe fe-user-check", type: 'link',path: `${process.env.PUBLIC_URL}/admin_dealers` ,active: false, selected: false,
  //         },
  //         { path: `${process.env.PUBLIC_URL}/admin_customers`, icon: 'fe fe-users', type: 'link', active: false, selected: false, title: 'Customers' },
  //         // { path: `${process.env.PUBLIC_URL}/logout`, icon: 'fe fe-log-out', type: 'link', active: false, selected: false, title: 'Log Out' },

  //     ]
  // },
];
